### ISSUE TITLE
Client authentication failed.

### ISSUE THREAD

**Issue by surjit** [uafrica/oauth-server#14]
I have this url http://cakephp.3/oauth/authorize?response_type=code&client_id=34556&client_secret=demo&redirect_uri=http://cakephp/client/receive_authcode

I'm getting error Client authentication failed.
League\OAuth2\Server\Exception\InvalidClientException

INSERT INTO `oauth_clients` (`id`, `client_secret`, `name`, `redirect_uri`, `parent_model`, `parent_id`) VALUES
('34556', 'demo', 'demo', 'http://http://cakephp.3/', NULL, NULL);

I Know, it's something I'm doing wrong, please guide me, how to fix this

**Comment by dakota** [comment]
The `redirect_uri` in the db needs to be identical to the one passed in by your client.

**Comment by surjit** [comment]
thanks, It's solved
