### ISSUE TITLE
Cannot use custom namespace for my Cake app

### ISSUE THREAD

**Issue by binarycrafts** [uafrica/oauth-server#44]
The plugin's controller `./vendor/uafrica/oauth-server/src/Controller/OAuthController.php` has `use App\Controller\AppController;` hardcoded which does not allow for a different namespace other than `App\`.

My workaround was to create a `./src/Controller/UafricaAppController.php`:
```
namespace App\Controller;

class AppController extends \MyCustomNamespace\Controller\AppController
{
    //
}
```
and load it from `composer.json` with:
```
    "autoload": {
        "psr-4": {
            "MyCustomNamespace\\": "src"
        },
        "files": ["src/Controller/UafricaAppController.php"]
    },
```

**Comment by dakota** [comment]
We are aware of this, but unfortunately, php doesn't allow us to extend a class based on an expression. All plugins that I'm aware of with controllers do the same thing.

In our own internal use, we do the same workaround as you've got (We also don't use the default namespace)

**Comment by binarycrafts** [comment]
Understood, thanks!

**Comment by sukihub** [comment]
Hi, can I suggest reopening this? I too find it weird to expect `\App\Controller\AppController` to exist. My workaround was this line in `bootstrap.php`:

```php
class_alias('MyCustomNamespace\Controller\MyAppController', 'App\Controller\AppController');
```

Maybe the AppController class can be specified in a config this way? And if it's not, just use default Controller class.
