### ISSUE TITLE
cakephp2 with oauth2 : Could not load configuration file: D:\harendar\htdocs\flow_beta\app\Config\OAuth.php

### ISSUE THREAD

**Issue by Harrrrry** [uafrica/oauth-server#53]
Hello All,
According to https://github.com/thomseddon/cakephp-oauth-server
I am using CakePHP 2 with oauth2 for API.
After all setup,  I am getting below error:

![collegeavenues errors](https://cloud.githubusercontent.com/assets/14884583/25171190/9599d0ce-250a-11e7-8dc1-f9edeed978b0.png)

I just want to setup OAuth with my cakephp2 API.
Please help me to figure out this problem.
Thanks,

**Comment by dakota** [comment]
Sorry, this plugin is for CakePHP 3 only.
