### ISSUE TITLE
CakePHP 3.4 and above

### ISSUE THREAD

**Issue by klickagent** [uafrica/oauth-server#54]
Hi there
I just noticed that many things are changing from version 3.3 to 3.4 in CakePHP. (https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html).

Has already someone integrated this plugin with the new version? Is there any assistance wanted to upgrade?

Best regards
Roman

**Comment by irongomme** [comment]
Hi, I've integrated this plugin into cake 3.4.7, and it works ... I think issues related to this plugin are still up to date.

**Comment by sukihub** [comment]
Hi, sorry for the delay, but yes, plugin works with 3.4 (with the exception of login redirect, fix will hopefully be merged soon - #58). We have it in production right now.

There is also a new version of league/oauth2-server that uses middleware, which should be usable in 3.4. Would be cool to have, but not necessary for now :)
