### ISSUE TITLE
Small documentation error

### ISSUE THREAD

**Issue by klickagent** [uafrica/oauth-server#7]
It is not an error in the library but I guess in the documentation on https://libraries.io/packagist/uafrica%2Foauth-server.

$this->Auth->config('authenticate', [
    'Form',
    'OAuthServer'
]);

should be

$this->Auth->config('authenticate', [
    'Form',
    'OAuthServer.OAuth'
]);

as it is in the documentation in your github repo.

**Comment by dakota** [comment]
We don't use libraries.io, I've in fact never heard of it until now! Looks like it just pulls in data from Packagist (Outdated data at that).

Please use the documentation in the repo instead of any other third-party mirror.

**Comment by dakota** [comment]
Thanks for reporting the error though! :+1:
